### ISSUE TITLE
Add button to enter game room once at least 2 players have joined

### ISSUE THREAD

**Issue by arorakarnika** [arorakarnika/Cluegonauts#5]
- Add a button to the character selection page to start the game. This button should be greyed out until the minimum number of players have joined.
- When any player clicks the "Start Game" button, the game should start automatically for all players. The message log should display a message like "Player 1 has started the game". The actual logic to start the game will be implemented in #6.

**Comment by agrove11** [comment]
FYI- I have started working on this.

**Comment by agrove11** [comment]
Draft (Checked in JSFiddle)

HTML

`<link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.12/dist/full.min.css" rel="stylesheet" type="text/css" />
<script src="https://cdn.tailwindcss.com"></script>

<html data-theme="cupcake"></html>

<div class="col-md-6">
    <h1>Join the Game</h1>
    <p>Which player would you like to be?</p>
    <select id="player-select" class="form-select">
        <option value="Miss Scarlett">Miss Scarlett</option>
        <option value="Colonel Mustard">Colonel Mustard</option>
        <option value="Mrs. Peacock">Mrs. Peacock</option>
        <option value="Mr. Green">Mr. Green</option>
        <option value="Dr. Orchid">Dr. Orchid</option>
        <option value="Professor Plum">Professor Plum</option>
    </select>
    <br>
    <input id="player-submit" type="button" value="Join Game" class="btn btn-primary"> <br>

    
    <input id="enter-game-room" type="button" value="Enter Game Room" class="btn bg-base-300 btn-success" disabled style="display:none;">
</div>
`


JAVA

`let playerCount = 0;

// Function to update the button state
function updateButtonState() {
    const enterButton = document.querySelector('#enter-game-room');
    if (playerCount >= 6) {
        // Enable the button and change color to blue (default Daisy UI theme button)
        enterButton.disabled = false;
        enterButton.classList.add('btn-primary');  // Blue color
        enterButton.classList.remove('btn');  // Remove default grey
    } else {
        // Keep the button disabled and grey
        enterButton.disabled = true;
        enterButton.classList.remove('btn-primary');  // Remove blue color
        enterButton.classList.add('btn');  // Keep default grey
    }
}

document.querySelector('#player-submit').onclick = function(e) {
    const selectedPlayer = document.querySelector('#player-select').value;
    
    // Send message to WebSocket (assuming you already have this working)
    activitySocket.send(JSON.stringify({
        'message': selectedPlayer + ' has joined the game.'
    }));

    playerCount += 1;  // Increment player count each time a player joins
    
    // Update the button state based on the player count
    updateButtonState();
};
`

**Comment by agrove11** [comment]
I am facing an issue setting up my local environment. I'll get the pull request in as soon as I have it resolved.
